image: sknnr/ark-ascended-server
imageTag: latest
# serviceType should be LoadBalancer or NodePort
serviceType: LoadBalancer
resources:
  requests:
    memory: 24G
    cpu: 4.0
volumes:
  dataPVC:
    size: 50Gi
  storageClassName: ""
env:
  worldZipUrl: ""
  overwrite: "false"
