name: Publish New Image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Semantic version to assign the new tag"
        required: true
        type: string

jobs:
  tag_repo:
    name: "Add New Tag to Repo"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "GitHub Tag"
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          image_tag: ${{ github.event.inputs.tag }}
          create_annotated_tag: true
  build_and_push_image:
    name: "Build and Push a New Image"
    runs-on: ubuntu-latest
    needs:
      - tag_repo
    steps:
      - uses: actions/checkout@v3
      - name: Set Variables
        id: variables
        run: |
          echo "::set-output name=dockerhubpath::sknnr/space-engineers-dedicated-server"
          echo "::set-output name=datetime::$(date +%Y%m%dT%H%M%SZ)"
      - name: "Login to Docker Hub"
        run: |
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }} docker.io
      - name: "Start Local Container Registry"
        run: |
          docker run --rm --detach --publish 5000:5000 --name registry docker.io/registry
      - name: "Build New Image"
        run: |
          docker build \
          --file ./docker/Dockerfile \
          --tag localhost:5000/${{ steps.variables.outputs.dockerhubpath }}:${{ github.event.inputs.tag }} \
          ./docker
      - name: "Push New Image to Local Container Registry"
        run: |
          docker push \
          localhost:5000/${{ steps.variables.outputs.dockerhubpath }}:${{ github.event.inputs.tag }}
      - name: "Inspect the New Image"
        run: |
          skopeo inspect \
          --tls-verify=false \
          docker://localhost:5000/${{ steps.variables.outputs.dockerhubpath }}:${{ github.event.inputs.tag }}
      - name: "Push the New Image to Docker Hub"
        run: |
          skopeo copy \
          --src-tls-verify=false \
          --dest-creds ${{ secrets.DOCKER_USER }}:${{ secrets.DOCKER_TOKEN }} \
          docker://localhost:5000/${{ steps.variables.outputs.dockerhubpath }}:${{ github.event.inputs.tag }} \
          docker://docker.io/${{ steps.variables.outputs.dockerhubpath }}:${{ github.event.inputs.tag }}
          skopeo copy \
          --src-tls-verify=false \
          --dest-creds ${{ secrets.DOCKER_USER }}:${{ secrets.DOCKER_TOKEN }} \
          docker://localhost:5000/${{ steps.variables.outputs.dockerhubpath }}:${{ github.event.inputs.tag }} \
          docker://docker.io/${{ steps.variables.outputs.dockerhubpath }}:latest
